kind: pipeline
name: api:node10

clone:
  depth: 1

steps:
- name: install-dependencies
  image: node:10
  commands:
    - cd api
    - npm ci
- name: run-tests
  image: node:10
  commands:
    - cd api
    - npm test
- name: run-coverage
  image: node:10
  commands:
    - cd api
    - ./node_modules/.bin/nyc npm test
    - ./node_modules/.bin/nyc report --reporter=text-lcov > coverage.lcov
    - ./node_modules/.bin/nyc report --reporter=text
- name: upload-coverage-report
  when:
    repo:
      - openunite/openunite
  image: node:10
  environment:
    CODECOV_TOKEN:
      from_secret: codecov_token
  commands:
    - cd api
    - ./node_modules/.bin/codecov --disable=gcov -f coverage.lcov

trigger:
  event:
  - push

---
kind: pipeline
name: api:node8

clone:
  depth: 1

steps:
- name: install-dependencies
  image: node:8
  commands:
    - cd api
    - npm ci
- name: run-tests
  image: node:8
  commands:
    - cd api
    - npm test

trigger:
  event:
  - push

---
kind: pipeline
name: web

clone:
  depth: 1

steps:
- name: install-dependencies
  image: node:10
  commands:
    - cd web
    - npm ci
- name: build
  image: node:10
  commands:
    - cd web
    - npm run build

trigger:
  event:
  - push
